name: Build and Deploy to IIS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0 # Change this to your required .NET version

    # Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore

    # Build the project
    - name: Build Project
      run: dotnet publish -c Release -o ./output

    # Archive build artifacts
    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-build
        path: ./output

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    # Download build artifacts
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: app-build

    # Deploy to IIS Server
    - name: Deploy to IIS
      uses: garygrossgarten/github-action-ftp@v3
      with:
        host: ${{ secrets.IIS_HOST }}
        username: ${{ secrets.IIS_USERNAME }}
        password: ${{ secrets.IIS_PASSWORD }}
        local-dir: ./output
        remote-dir: /path/to/your/iis/site # Update this with your IIS site path

    # Restart IIS Application Pool
    - name
