name: Build and Deploy to IIS on Commit

on:
  push:  # Trigger workflow on commits to any branch
    branches:
      - '**'  # Or specify branches like 'main'

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0 

    # Step 3: Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore

    # Step 4: Build and Publish the project
    - name: Build Project
      run: dotnet publish -c Release -o ./output

    # Step 5: Upload build artifacts for later use
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-build
        path: ./output

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    # Step 1: Download the artifact from GitHub Actions
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: app-build  # Artifact name must match the one used in the build job
        path: ./artifact-dir  # Destination folder to store the downloaded artifact

    # Step 2: Deploy to IIS Server via FTP using SamKirkland/ftp-deploy-action
    - name: Deploy to IIS via FTP
      uses: SamKirkland/ftp-deploy-action@v4.0.0  # Alternative FTP action
      with:
        server: ${{ secrets.IIS_HOST }}
        username: ${{ secrets.IIS_USERNAME }}
        password: ${{ secrets.IIS_PASSWORD }}
        local-dir: ./artifact-dir  # Path to the downloaded artifact directory
        remote-dir: C:\inetpub\wwwroot\demo-app  # Replace with your IIS site directory

    # Step 3: Restart IIS Application Pool (optional)
    - name: Restart IIS Application Pool
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.IIS_USERNAME }}@${{ secrets.IIS_HOST }} "powershell Restart-WebAppPool -Name 'YourAppPoolName'"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 4: Deploy via PowerShell to IIS (alternative to FTP)
    - name: Deploy via PowerShell to IIS (alternative to FTP)
      run: |
        $sourcePath = "$(System.DefaultWorkingDirectory)\artifact-dir"  # Path to downloaded artifact
        $destinationPath = "C:\inetpub\wwwroot\demo-app"  # Update this path to your IIS site
        # Stop IIS App Pool (optional)
        Stop-WebAppPool -Name "apt-booking"
        # Copy files to IIS site directory
        Copy-Item -Path $sourcePath\* -Destination $destinationPath -Recurse -Force
        # Start IIS App Pool
        Start-WebAppPool -Name "apt-booking"
      shell: pwsh
      env:
        IIS_USERNAME: ${{ secrets.IIS_USERNAME }}
        IIS_PASSWORD: ${{ secrets.IIS_PASSWORD }}

    # Step 5: Restart IIS Application Pool again (optional)
    - name: Restart IIS Application Pool Again (optional)
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.IIS_USERNAME }}@${{ secrets.IIS_HOST }} "powershell Restart-WebAppPool -Name 'YourAppPoolName'"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
